//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSite_ShowRoom_CtyThoiTrang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_KhoReturn
    {
        public int IdKhoXuat { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public string ReturnBy { get; set; }
        public string MSNV { get; set; }
        public int ReturnId { get; set; }
        public int IdKho { get; set; }
    
        public virtual tb_Kho tb_Kho { get; set; }
        public virtual tb_NhanVien tb_NhanVien { get; set; }
        public virtual tb_Return tb_Return { get; set; }
    }
}
