//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSite_ShowRoom_CtyThoiTrang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_KhoXuat
    {
        public int IdKhoXuat { get; set; }
        public System.DateTime OutDate { get; set; }
        public string OutBy { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> Idkho { get; set; }
        public string MSNV { get; set; }
    
        public virtual tb_Kho tb_Kho { get; set; }
        public virtual tb_NhanVien tb_NhanVien { get; set; }
        public virtual tb_Order tb_Order { get; set; }
    }
}
