//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSite_ShowRoom_CtyThoiTrang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_NhanVien()
        {
            this.tb_KhoNhap = new HashSet<tb_KhoNhap>();
            this.tb_KhoReturn = new HashSet<tb_KhoReturn>();
            this.tb_KhoXuat = new HashSet<tb_KhoXuat>();
            this.tb_NhanVienImage = new HashSet<tb_NhanVienImage>();
            this.tb_PhanQuyen = new HashSet<tb_PhanQuyen>();
        }
    
        public string MSNV { get; set; }
        public string SDT { get; set; }
        public string TenNhanVien { get; set; }
        public string CCCD { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Image { get; set; }
        public System.DateTime Birthday { get; set; }
        public string DiaChi { get; set; }
        public Nullable<System.DateTime> NgayVaoLam { get; set; }
        public decimal Luong { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> IdChucNang { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> Clock { get; set; }
    
        public virtual tb_ChucNang tb_ChucNang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_KhoNhap> tb_KhoNhap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_KhoReturn> tb_KhoReturn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_KhoXuat> tb_KhoXuat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_NhanVienImage> tb_NhanVienImage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_PhanQuyen> tb_PhanQuyen { get; set; }
    }
}
